abatilo/actions-poetry

Dockerfile, action.yml
We were previously using the original Actions v1 metadata setup. This
updates the metadata to be displayed in the GitHub Marketplace
=> chore: update metadata format

.github/workflows/ci.yml, Dockerfile, action.yml, entrypoint.sh
This change allows you to under specify a version of Python, such as
dropping the patch version number, and the action will still work. This
works even if you drop the minor version number and the patch version
number.
We're using the https://github.com/momo-lab/xxenv-latest plugin to find
the latest version of Python based on whatever version you gave it.
Fixes #12
=> feat: Support under specified versions of Python

.github/workflows/ci.yml, README.md, action.yml, entrypoint.sh
This PR contains a change that allows the user of the action to specify a working directory where their project is located. Currently, this action assumes that the `pyproject.toml` is located in the root of the repository, which isn't always the case.
Other minor changes include changing the entrypoint shell from `sh` to `bash` and some shell style fixes (as indicated by [shellcheck](https://github.com/koalaman/shellcheck)).
=> feat: Adds working_directory Input to Action

entrypoint.sh
The `__pycache__` files generated during `docker build` would be a `root:root` permission which will make the further build error in the host. I have this issue both in the `self hosted` env and the default github `ubuntu` container.
=> fix: remove pycache to aviod further permission error

.github/workflows/ci.yml, README.md, action.yml
Version 1.1.2 [was released a week ago](https://github.com/python-poetry/poetry/releases), should this action use the latest by default?
=> feat: Update default poetry version to 1.1.2

.github/workflows/ci.yml, README.md
Previously, the python version 3.10 was parsed as a 3.1 because the number 3.10 is the same as 3.1.
Quoting it as a string fixes the parsing, where it correctly reads it as "3.10"
Additionally, introduced python versions 3.9 and 3.10.
Relates to #46
=> fix: quote versions to fix parsing errors

action.yml
https://github.com/python-poetry/poetry/releases/tag/1.1.15 is released
=> fix: Updating default poetry version to 1.15

README.md
Thank you very much for responding to my request in #51.
This is a small follow-up to recommend users to use the major version tag.
=> docs: Use major version for version expression in the example in README

.github/workflows/ci.yml
Ubuntu 18.04 is being deprecated in 3 months.
https://github.com/actions/runner-images/issues/6002
=> ci: Upgrade to ubuntu-20.04 from ubuntu-18.04

.github/workflows/ci.yml, action.yml
Hello,
with this PR the input variable `poetry-version` is no longer a required parameter.
By default the latest version of Poetry will be installed. If a user requires a specific version, it still can be specified with the `poetry-version` variable like before.
=> feat: by default use the latest poetry version

README.md
=> docs: caching venv

.github/workflows/ci.yml, .github/workflows/lint-pr.yml, README.md, action.yml
So starting somewhat time soon Poetry will not install plugins (such as export plugin e.g.) by default. So this PR add ability to install plugins by default and also installs the export plugin for you by default.
As part of the PR I have also updated versions of the GH actions used in workflows.
=> feat: Add ability to install plugins as part of the action setup

.github/workflows/ci.yml
This will make it so that I can make the success of ci-all be the
required step for branch protection rules. That way, if the combination
of versions of Python and OS change, then I don't have to change the
branch protection rules themselves.
=> ci: Create catch-all GHA job

action.yml
Following poetry recommendation, it better to use pipx instead of pip to avoid mixing application dependencies with poetry's 
https://python-poetry.org/docs/#ci-recommendations
BREAKING CHANGE: Switch using an isolated pipx virtualenv
=> feat!: use pipx to isolate poetry

README.md
I had this confusion because I think I skimmed the `README` too quickly. This PR makes the distinction clear
=> docs: Making no `pyproject.toml` support clear

.github/workflows/ci.yml, action.yml
Related to #74
Add support for installing the latest `main` branch commit of Poetry.
* **action.yml**
- Add a new condition to check if `poetry-version` is "main".
- Add a new step to install the latest `main` branch commit of Poetry if `poetry-version` is "main".
- Update the condition for installing specific versions of Poetry to exclude "main".
* **.github/workflows/ci.yml**
- Add "main" to the `poetry-version` matrix.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/abatilo/actions-poetry/issues/74?shareId=2232111d-c069-4cf5-b846-f192c9c69571).
=> feat: Support latest main branch commit for poetry-version

action.yml
Fixes #68 by explicitly calling `python3 -m pip install`
Signed-off-by: Tiago Reis <tiagovrtreis@gmail.com>
=> fix: ubuntu pipx installation by calling pip from python3

.github/workflows/ci.yml, README.md
It's been a long time since I've updated the test matrix. Python 3.8 has
been end of lifed for a while.
=> ci: Update test matrix

.github/workflows/ci.yml
We had a breaking change and I should have stopped updating v2 as a
moving tag.
This was highlighted by @mmontesi in https://github.com/abatilo/actions-poetry/issues/76#issuecomment-2442182667
=> ci: Only auto update v3

.github/workflows/ci.yml
We're about to merge a change that will start as v4, and we don't want
to replace what `v3` has
=> ci: Disable pushing to major version tag

action.yml
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
https://github.com/actions/runner-images/blob/main/README.md#package-managers-usage
=> fix!: pipx is pre-installed in GitHub Actions
